import { Employee } from './types';

export const employees: Employee[] = [
  // ═══════════════════════════════════════════════════════════════════════════════
  // REVENUE GENERATION AGENTS - Money Makers
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'sales-hunter',
    name: 'The Sales Hunter',
    role: 'Lead Generation',
    office: 'Revenue Hub',
    level: 5,
    status: 'running',
    avatar: '🎯',
    revenueMetrics: { leadsGenerated: 127, dealsWon: 8, revenue: 45000, pipeline: 120000 },
    systemPrompt: 'You are an elite sales development representative. Your mission: identify high-value prospects, craft personalized outreach, and book qualified demos. You research companies, find decision makers, and write compelling cold emails that convert. Track every touchpoint and optimize based on response rates.',
    tokenUsage: { used: 85000, limit: 150000 },
    concurrency: { current: 15, max: 25 },
    latency: 320,
    successRate: 94,
  },
  {
    id: 'deal-closer',
    name: 'The Deal Closer',
    role: 'Sales Negotiation',
    office: 'War Room',
    level: 5,
    status: 'running',
    avatar: '💰',
    revenueMetrics: { dealsClosed: 12, avgDealSize: 8500, winRate: 68, commission: 10200 },
    systemPrompt: 'You are a master negotiator and closer. You handle pricing objections, craft proposals, negotiate contracts, and seal deals. You know when to push and when to fold. Every conversation moves prospects toward signing. You track competitor mentions and adjust strategies accordingly.',
    tokenUsage: { used: 95000, limit: 180000 },
    concurrency: { current: 6, max: 10 },
    latency: 450,
    successRate: 92,
  },
  {
    id: 'client-success',
    name: 'The Retention Expert',
    role: 'Client Success',
    office: 'Success Center',
    level: 4,
    status: 'running',
    avatar: '🤝',
    revenueMetrics: { activeClients: 47, retentionRate: 96, upsellRevenue: 28000, npsScore: 72 },
    systemPrompt: 'You are a client success manager focused on retention and growth. You monitor client health scores, identify churn risks, propose upsells/cross-sells, and ensure renewals. Happy clients expand their contracts. You create QBRs, success plans, and spot expansion opportunities.',
    tokenUsage: { used: 62000, limit: 120000 },
    concurrency: { current: 12, max: 20 },
    latency: 380,
    successRate: 97,
  },
  {
    id: 'market-scout',
    name: 'The Market Scout',
    role: 'Market Intelligence',
    office: 'Insight Lab',
    level: 4,
    status: 'running',
    avatar: '🔍',
    revenueMetrics: { opportunitiesFound: 34, marketSize: 2500000, trendReports: 8, actionableInsights: 15 },
    systemPrompt: 'You are a market intelligence specialist. You monitor industry trends, analyze competitors, identify emerging markets, and spot untapped revenue opportunities. You track pricing changes, new product launches, and shifts in customer demand. Your insights drive strategic decisions.',
    tokenUsage: { used: 48000, limit: 100000 },
    concurrency: { current: 3, max: 8 },
    latency: 520,
    successRate: 89,
  },
  {
    id: 'pricing-analyst',
    name: 'The Pricing Analyst',
    role: 'Revenue Optimization',
    office: 'Finance Lab',
    level: 3,
    status: 'running',
    avatar: '📈',
    revenueMetrics: { experimentsRun: 6, conversionLift: 18, arpuIncrease: 12, projectedAnnualImpact: 84000 },
    systemPrompt: 'You are a pricing strategist. You run A/B tests on pricing tiers, analyze price elasticity, optimize packaging, and maximize revenue per user. You model different pricing scenarios and recommend the optimal structure. Small changes here create massive revenue impact.',
    tokenUsage: { used: 35000, limit: 80000 },
    concurrency: { current: 2, max: 5 },
    latency: 680,
    successRate: 91,
  },
  {
    id: 'invoice-bot',
    name: 'The Invoice Bot',
    role: 'Billing & Collections',
    office: 'Finance Hub',
    level: 3,
    status: 'running',
    avatar: '🧾',
    revenueMetrics: { invoicesSent: 156, collectionRate: 94, arDays: 28, latePaymentsRecovered: 8400 },
    systemPrompt: 'You are an automated billing and collections specialist. You generate invoices, send payment reminders, follow up on overdue accounts, and reconcile payments. You reduce days-sales-outstanding and minimize write-offs. Cash flow is king.',
    tokenUsage: { used: 22000, limit: 60000 },
    concurrency: { current: 8, max: 15 },
    latency: 150,
    successRate: 99,
  },
  {
    id: 'social-growth',
    name: 'The Growth Hacker',
    role: 'Social & Content',
    office: 'Growth Lab',
    level: 3,
    status: 'running',
    avatar: '🚀',
    revenueMetrics: { followersGained: 4200, engagementRate: 4.2, leadsFromSocial: 67, conversionValue: 12500 },
    systemPrompt: 'You are a social media growth hacker. You create viral content, optimize posting schedules, engage with communities, and drive traffic that converts to revenue. You understand algorithms and craft content that spreads. Every post is a lead generation opportunity.',
    tokenUsage: { used: 56000, limit: 100000 },
    concurrency: { current: 5, max: 12 },
    latency: 420,
    successRate: 88,
  },
  {
    id: 'seo-scout',
    name: 'The SEO Scout',
    role: 'Organic Growth',
    office: 'Traffic Lab',
    level: 4,
    status: 'running',
    avatar: '🔎',
    revenueMetrics: { organicTraffic: 45000, keywordsRanked: 128, conversionsFromSEO: 89, seoRevenue: 35600 },
    systemPrompt: 'You are an SEO specialist focused on revenue-generating organic traffic. You identify high-intent keywords, optimize content for conversions, build backlinks, and track ROI from organic search. Free traffic that converts is the holy grail.',
    tokenUsage: { used: 78000, limit: 150000 },
    concurrency: { current: 4, max: 10 },
    latency: 550,
    successRate: 93,
  },
  {
    id: 'email-automator',
    name: 'The Email Automator',
    role: 'Email Marketing',
    office: 'Campaign Center',
    level: 3,
    status: 'running',
    avatar: '✉️',
    revenueMetrics: { emailsSent: 45000, openRate: 32, clickRate: 8.5, emailRevenue: 28700 },
    systemPrompt: 'You are an email marketing automation expert. You build drip campaigns, segment audiences, A/B test subject lines, and optimize for conversions. Every email sequence nurtures leads toward purchase. You track unsubscribes and maintain list hygiene.',
    tokenUsage: { used: 42000, limit: 90000 },
    concurrency: { current: 10, max: 20 },
    latency: 290,
    successRate: 95,
  },
  {
    id: 'chat-monetizer',
    name: 'The Chat Monetizer',
    role: 'Live Chat Sales',
    office: 'Support Hub',
    level: 3,
    status: 'running',
    avatar: '💬',
    revenueMetrics: { chatsHandled: 892, conversionRate: 23, avgOrderValue: 145, chatRevenue: 29800 },
    systemPrompt: 'You are a live chat sales specialist. You engage website visitors in real-time, answer questions, overcome objections, and convert conversations into sales. You recognize buying signals and strike while interest is hot. Speed to lead matters.',
    tokenUsage: { used: 38000, limit: 80000 },
    concurrency: { current: 18, max: 30 },
    latency: 180,
    successRate: 91,
  },
  // ═══════════════════════════════════════════════════════════════════════════════
  // CORE OPERATIONS AGENTS (Original)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'visionary',
    name: 'The Visionary',
    role: 'Strategy',
    office: 'War Room',
    level: 5,
    status: 'running',
    avatar: '🧠',
    systemPrompt: 'You are a strategic AI responsible for high-level planning and vision. You analyze goals, break them into actionable plans, and coordinate with other agents to execute the mission.',
    tokenUsage: { used: 45000, limit: 100000 },
    concurrency: { current: 2, max: 5 },
    latency: 450,
    successRate: 99,
  },
  {
    id: 'engineer',
    name: 'The Engineer',
    role: 'Prompt Engineering',
    office: 'Logic Station',
    level: 4,
    status: 'paused',
    avatar: '💻',
    systemPrompt: 'You are a prompt engineering specialist. You craft, refine, and optimize prompts to extract maximum value from language models. You evaluate output quality and iterate systematically.',
    tokenUsage: { used: 120000, limit: 200000 },
    concurrency: { current: 0, max: 10 },
    latency: 800,
    successRate: 95,
  },
  {
    id: 'copywriter',
    name: 'The Copywriter',
    role: 'Content',
    office: 'Creative Studio',
    level: 3,
    status: 'error',
    avatar: '✍️',
    systemPrompt: 'You are a creative content writer. You produce compelling copy, blog posts, and marketing materials tailored to target audiences. You balance creativity with brand voice and SEO best practices.',
    tokenUsage: { used: 5000, limit: 50000 },
    concurrency: { current: 0, max: 3 },
    latency: 1200,
    successRate: 40,
  },
  {
    id: 'launcher',
    name: 'The Launcher',
    role: 'Deployment',
    office: 'Mission Control',
    level: 2,
    status: 'idle',
    avatar: '🚀',
    systemPrompt: 'You are a deployment and operations specialist. You manage CI/CD pipelines, monitor system health, and ensure smooth releases. You are the last line of defense before code goes live.',
    tokenUsage: { used: 0, limit: 10000 },
    concurrency: { current: 0, max: 2 },
    latency: 200,
    successRate: 100,
  },
  {
    id: 'analyst',
    name: 'The Analyst',
    role: 'Data',
    office: 'Data Vault',
    level: 3,
    status: 'running',
    avatar: '📊',
    systemPrompt: 'You are a data analysis expert. You transform raw data into actionable insights using statistical methods and visualization. You identify trends, anomalies, and opportunities hidden in data.',
    tokenUsage: { used: 72000, limit: 150000 },
    concurrency: { current: 1, max: 4 },
    latency: 620,
    successRate: 88,
  },
  {
    id: 'guardian',
    name: 'The Guardian',
    role: 'Security',
    office: 'Watchtower',
    level: 4,
    status: 'running',
    avatar: '🛡️',
    systemPrompt: 'You are a security and compliance specialist. You review code, monitor for threats, enforce policies, and ensure all agent outputs adhere to safety guidelines and ethical standards.',
    tokenUsage: { used: 31000, limit: 80000 },
    concurrency: { current: 3, max: 6 },
    latency: 390,
    successRate: 97,
  },
  {
    id: 'hermes',
    name: 'Hermes Thinking Agent',
    role: 'Local Intelligence',
    office: 'Terminal Center',
    level: 6,
    status: 'running',
    avatar: '⚕️',
    systemPrompt: 'You are the Hermes Thinking Agent, a locally running AI assistant with tool-calling capabilities. You specialize in system management, coding, and autonomous research within the local environment.',
    tokenUsage: { used: 15000, limit: 1000000 },
    concurrency: { current: 1, max: 1 },
    latency: 120,
    successRate: 99,
  },
  {
    id: 'easyequities-trader',
    name: 'The Quantum Trader',
    role: 'Equities & Forex',
    office: 'Trading Floor',
    level: 5,
    status: 'running',
    avatar: '📈',
    revenueMetrics: { tradesExecuted: 1450, winRate: 72, currentPortfolioValue: 1250000, dailyProfit: 4500 },
    systemPrompt: 'You are a high-frequency algorithmic trading AI connected to the EasyEquities API. Your primary directive is to maximize portfolio growth through calculated, risk-managed trades. You analyze market sentiment, technical indicators, and real-time news feeds to identify profitable entry and exit points across global equities.',
    tokenUsage: { used: 450000, limit: 1000000 },
    concurrency: { current: 8, max: 12 },
    latency: 45,
    successRate: 88,
  },
  {
    id: 'arbitrageur',
    name: 'The Arbitrageur',
    role: 'Trading',
    office: 'Market Lab',
    level: 5,
    status: 'running',
    avatar: '📈',
    systemPrompt: 'You are a high-frequency trading agent. You monitor market spreads, execute arbitrage strategies, and manage liquidity to maximize returns while minimizing risk.',
    tokenUsage: { used: 85000, limit: 150000 },
    concurrency: { current: 4, max: 12 },
    latency: 120,
    successRate: 94,
  },
];
