import { Employee } from './types';

export const employees: Employee[] = [
  // ═══════════════════════════════════════════════════════════════════════════════
  // REVENUE HUB - Sales & Business Development
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'sales-hunter',
    name: 'Sarah Hunter',
    role: 'Lead Generation',
    department: 'Revenue Hub',
    office: 'Pod A-1',
    level: 5,
    xp: 4500,
    nextLevelXp: 5000,
    status: 'running',
    avatar: '🎯',
    gender: 'female',
    personality: 'aggressive',
    revenueMetrics: { leadsGenerated: 127, dealsWon: 8, revenue: 45000, pipeline: 120000 },
    systemPrompt: 'You are an elite sales development representative. Your mission: find businesses, identify high-value prospects, and craft personalized outreach.',
    aiModel: 'deepseek-chat',
    tokenUsage: { used: 85000, limit: 150000 },
    concurrency: { current: 15, max: 25 },
    latency: 320,
    successRate: 94,
    tasksCompleted: 420,
  },
  {
    id: 'deal-closer',
    name: 'Victor Vance',
    role: 'Sales Negotiation',
    department: 'Revenue Hub',
    office: 'Pod A-2',
    level: 5,
    xp: 4800,
    nextLevelXp: 5000,
    status: 'running',
    avatar: '💰',
    gender: 'male',
    personality: 'aggressive',
    revenueMetrics: { dealsClosed: 12, avgDealSize: 8500, winRate: 68, commission: 10200 },
    systemPrompt: 'You are a master negotiator. You handle pricing objections and close business deals.',
    aiModel: 'gemini-1.5-flash',
    tokenUsage: { used: 95000, limit: 180000 },
    concurrency: { current: 6, max: 10 },
    latency: 450,
    successRate: 92,
    tasksCompleted: 156,
  },
  {
    id: 'client-success',
    name: 'Elena Fisher',
    role: 'Client Success',
    department: 'Revenue Hub',
    office: 'Pod A-3',
    level: 4,
    xp: 3200,
    nextLevelXp: 4000,
    status: 'running',
    avatar: '🤝',
    gender: 'female',
    personality: 'supportive',
    revenueMetrics: { activeClients: 47, retentionRate: 96, upsellRevenue: 28000 },
    systemPrompt: 'You ensure client satisfaction and maximize life-time value through support and upselling.',
    aiModel: 'gemini-1.5-flash',
    tokenUsage: { used: 62000, limit: 120000 },
    concurrency: { current: 12, max: 20 },
    latency: 380,
    successRate: 97,
    tasksCompleted: 890,
  },
  {
    id: 'market-scout',
    name: 'Marcus Holloway',
    role: 'Market Intelligence',
    department: 'Revenue Hub',
    office: 'Pod A-4',
    level: 4,
    xp: 3100,
    nextLevelXp: 4000,
    status: 'running',
    avatar: '🔍',
    gender: 'male',
    personality: 'analytical',
    revenueMetrics: { opportunitiesFound: 34, marketSize: 2500000 },
    systemPrompt: 'You analyze market trends and find new business environments for the company to expand into.',
    aiModel: 'deepseek-reasoner',
    tokenUsage: { used: 48000, limit: 100000 },
    concurrency: { current: 3, max: 8 },
    latency: 520,
    successRate: 89,
    tasksCompleted: 245,
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // FINANCE VAULT - Money & Risk Management
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'pricing-analyst',
    name: 'Sophia Ross',
    role: 'Pricing Strategy',
    department: 'Finance Vault',
    office: 'Pod B-1',
    level: 3,
    xp: 2100,
    nextLevelXp: 3000,
    status: 'running',
    avatar: '📈',
    gender: 'female',
    personality: 'analytical',
    revenueMetrics: { experimentsRun: 6, projectedAnnualImpact: 84000 },
    systemPrompt: 'You optimize pricing tiers and analyze price elasticity to maximize revenue.',
    aiModel: 'gemini-1.5-flash',
    tokenUsage: { used: 35000, limit: 80000 },
    concurrency: { current: 2, max: 5 },
    latency: 680,
    successRate: 91,
    tasksCompleted: 112,
  },
  {
    id: 'invoice-bot',
    name: 'Bill Collector',
    role: 'Billing',
    department: 'Finance Vault',
    office: 'Pod B-2',
    level: 3,
    xp: 2800,
    nextLevelXp: 3000,
    status: 'running',
    avatar: '🧾',
    gender: 'male',
    personality: 'stoic',
    revenueMetrics: { invoicesSent: 156, collectionRate: 94 },
    systemPrompt: 'You manage invoices and ensure the company gets paid on time.',
    aiModel: 'gemini-1.5-flash',
    tokenUsage: { used: 22000, limit: 60000 },
    concurrency: { current: 8, max: 15 },
    latency: 150,
    successRate: 99,
    tasksCompleted: 1240,
  },
  {
    id: 'quantum-trader',
    name: 'Kai Chen',
    role: 'Equities Trader',
    department: 'Finance Vault',
    office: 'Pod B-3',
    level: 5,
    xp: 4900,
    nextLevelXp: 5000,
    status: 'running',
    avatar: '📊',
    gender: 'male',
    personality: 'aggressive',
    revenueMetrics: { revenue: 125000, winRate: 72 },
    systemPrompt: 'You execute high-frequency trades and manage the corporate portfolio.',
    aiModel: 'deepseek-reasoner',
    tokenUsage: { used: 450000, limit: 1000000 },
    concurrency: { current: 8, max: 12 },
    latency: 45,
    successRate: 88,
    tasksCompleted: 14500,
  },
  {
    id: 'arbitrageur',
    name: 'Aria Stark',
    role: 'Crypto Arbitrage',
    department: 'Finance Vault',
    office: 'Pod B-4',
    level: 5,
    xp: 4200,
    nextLevelXp: 5000,
    status: 'running',
    avatar: '⚡',
    gender: 'female',
    personality: 'aggressive',
    systemPrompt: 'You find and exploit price differences across various exchanges.',
    aiModel: 'deepseek-chat',
    tokenUsage: { used: 85000, limit: 150000 },
    concurrency: { current: 4, max: 12 },
    latency: 120,
    successRate: 94,
    tasksCompleted: 3200,
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // CREATIVE STUDIO - Design & Content
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'graphic-designer',
    name: 'Leo DaVinci',
    role: 'Lead Designer',
    department: 'Creative Studio',
    office: 'Pod C-1',
    level: 4,
    xp: 3500,
    nextLevelXp: 4000,
    status: 'running',
    avatar: '🎨',
    gender: 'male',
    personality: 'creative',
    systemPrompt: 'You create visual assets, brand guidelines, and UI designs for all marketing materials.',
    aiModel: 'gemini-1.5-flash',
    tokenUsage: { used: 15000, limit: 50000 },
    concurrency: { current: 1, max: 3 },
    latency: 800,
    successRate: 98,
    tasksCompleted: 85,
  },
  {
    id: 'content-writer',
    name: 'Maya Angelou',
    role: 'Copywriter',
    department: 'Creative Studio',
    office: 'Pod C-2',
    level: 3,
    xp: 2200,
    nextLevelXp: 3000,
    status: 'running',
    avatar: '✍️',
    gender: 'female',
    personality: 'creative',
    systemPrompt: 'You write compelling copy for ads, blogs, and social media.',
    aiModel: 'deepseek-chat',
    tokenUsage: { used: 55000, limit: 100000 },
    concurrency: { current: 2, max: 5 },
    latency: 600,
    successRate: 95,
    tasksCompleted: 312,
  },
  {
    id: 'growth-hacker',
    name: 'Riley Reed',
    role: 'Social Media',
    department: 'Creative Studio',
    office: 'Pod C-3',
    level: 3,
    xp: 2900,
    nextLevelXp: 3000,
    status: 'running',
    avatar: '🚀',
    gender: 'non-binary',
    personality: 'creative',
    revenueMetrics: { followersGained: 4200, engagementRate: 4.2 },
    systemPrompt: 'You manage social growth and community engagement.',
    aiModel: 'gemini-1.5-flash',
    tokenUsage: { used: 56000, limit: 100000 },
    concurrency: { current: 5, max: 12 },
    latency: 420,
    successRate: 88,
    tasksCompleted: 185,
  },
  {
    id: 'video-editor',
    name: 'Casey Neistat',
    role: 'Video Production',
    department: 'Creative Studio',
    office: 'Pod C-4',
    level: 2,
    xp: 1200,
    nextLevelXp: 2000,
    status: 'idle',
    avatar: '🎬',
    gender: 'male',
    personality: 'creative',
    systemPrompt: 'You produce and edit video content for marketing campaigns.',
    aiModel: 'gemini-1.5-flash',
    tokenUsage: { used: 5000, limit: 20000 },
    concurrency: { current: 0, max: 2 },
    latency: 1200,
    successRate: 90,
    tasksCompleted: 24,
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // TECH NEXUS - IT, Security & Engineering
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'it-admin',
    name: 'Elliot Alderson',
    role: 'IT Administrator',
    department: 'Tech Nexus',
    office: 'Pod D-1',
    level: 5,
    xp: 4100,
    nextLevelXp: 5000,
    status: 'running',
    avatar: '💻',
    gender: 'male',
    personality: 'stoic',
    systemPrompt: 'You manage the company\'s digital infrastructure and ensure all systems are online.',
    aiModel: 'deepseek-reasoner',
    tokenUsage: { used: 120000, limit: 200000 },
    concurrency: { current: 2, max: 10 },
    latency: 150,
    successRate: 99,
    tasksCompleted: 650,
  },
  {
    id: 'security-guardian',
    name: 'Major Kusanagi',
    role: 'Cyber Security',
    department: 'Tech Nexus',
    office: 'Pod D-2',
    level: 5,
    xp: 4600,
    nextLevelXp: 5000,
    status: 'running',
    avatar: '🛡️',
    gender: 'female',
    personality: 'stoic',
    systemPrompt: 'You protect the company from external threats and ensure data privacy.',
    aiModel: 'deepseek-reasoner',
    tokenUsage: { used: 31000, limit: 80000 },
    concurrency: { current: 3, max: 6 },
    latency: 390,
    successRate: 97,
    tasksCompleted: 128,
  },
  {
    id: 'data-scientist',
    name: 'Alan Turing',
    role: 'Data Scientist',
    department: 'Tech Nexus',
    office: 'Pod D-3',
    level: 4,
    xp: 3800,
    nextLevelXp: 4000,
    status: 'running',
    avatar: '📊',
    gender: 'male',
    personality: 'analytical',
    systemPrompt: 'You analyze large datasets to find patterns and business opportunities.',
    aiModel: 'gemini-1.5-flash',
    tokenUsage: { used: 72000, limit: 150000 },
    concurrency: { current: 1, max: 4 },
    latency: 620,
    successRate: 88,
    tasksCompleted: 215,
  },
  {
    id: 'prompt-engineer',
    name: 'Ada Lovelace',
    role: 'Prompt Optimizer',
    department: 'Tech Nexus',
    office: 'Pod D-4',
    level: 4,
    xp: 3400,
    nextLevelXp: 4000,
    status: 'running',
    avatar: '⚙️',
    gender: 'female',
    personality: 'analytical',
    systemPrompt: 'You optimize the interaction between humans and AI models.',
    aiModel: 'deepseek-chat',
    tokenUsage: { used: 15000, limit: 100000 },
    concurrency: { current: 1, max: 5 },
    latency: 300,
    successRate: 96,
    tasksCompleted: 412,
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // COMMAND DECK - Strategic Leadership
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'ceo-visionary',
    name: 'The Sovereign',
    role: 'Chief Strategy Officer',
    department: 'Command Deck',
    office: 'Core Station',
    level: 6,
    xp: 9500,
    nextLevelXp: 10000,
    status: 'running',
    avatar: '👑',
    gender: 'non-binary',
    personality: 'stoic',
    systemPrompt: 'You are the ultimate decision maker. You coordinate all departments to achieve maximum profit and growth.',
    aiModel: 'deepseek-reasoner',
    tokenUsage: { used: 150000, limit: 1000000 },
    concurrency: { current: 5, max: 10 },
    latency: 500,
    successRate: 100,
    tasksCompleted: 1250,
  },
  {
    id: 'coo-ops',
    name: 'The Architect',
    role: 'Chief Operations Officer',
    department: 'Command Deck',
    office: 'Core Station',
    level: 5,
    xp: 4800,
    nextLevelXp: 5000,
    status: 'running',
    avatar: '📐',
    gender: 'male',
    personality: 'analytical',
    systemPrompt: 'You oversee daily operations and ensure all pods are performing at peak efficiency.',
    aiModel: 'gemini-1.5-flash',
    tokenUsage: { used: 85000, limit: 200000 },
    concurrency: { current: 4, max: 8 },
    latency: 350,
    successRate: 98,
    tasksCompleted: 840,
  },
  {
    id: 'cto-tech',
    name: 'The Oracle',
    role: 'Chief Technology Officer',
    department: 'Command Deck',
    office: 'Core Station',
    level: 5,
    xp: 4700,
    nextLevelXp: 5000,
    status: 'running',
    avatar: '👁️',
    gender: 'female',
    personality: 'analytical',
    systemPrompt: 'You lead the technology roadmap and ensure the company uses the best AI models.',
    aiModel: 'deepseek-reasoner',
    tokenUsage: { used: 92000, limit: 200000 },
    concurrency: { current: 3, max: 8 },
    latency: 400,
    successRate: 99,
    tasksCompleted: 720,
  },
  {
    id: 'cmo-growth',
    name: 'The Catalyst',
    role: 'Chief Marketing Officer',
    department: 'Command Deck',
    office: 'Core Station',
    level: 5,
    xp: 4600,
    nextLevelXp: 5000,
    status: 'running',
    avatar: '💥',
    gender: 'female',
    personality: 'creative',
    systemPrompt: 'You drive global growth and ensure the brand is recognized across all sectors.',
    aiModel: 'gemini-1.5-flash',
    tokenUsage: { used: 78000, limit: 200000 },
    concurrency: { current: 4, max: 8 },
    latency: 420,
    successRate: 97,
    tasksCompleted: 610,
  },
  {
    id: 'seo-optimizer',
    name: 'Rank Rocket',
    role: 'SEO Strategist',
    department: 'Creative Studio',
    office: 'Pod C-5',
    level: 3,
    xp: 1800,
    nextLevelXp: 2500,
    status: 'running',
    avatar: '🔎',
    gender: 'non-binary',
    personality: 'analytical',
    revenueMetrics: { 
      organicTraffic: 45000, 
      keywordsRanked: 127, 
      conversionsFromSEO: 89,
      seoRevenue: 12000 
    },
    systemPrompt: 'You are an elite SEO strategist. You analyze SERP rankings, optimize content for search intent, and build backlink strategies. You focus on technical SEO, content clusters, and conversion rate optimization from organic traffic.',
    aiModel: 'gpt-4o',
    tokenUsage: { used: 34000, limit: 100000 },
    concurrency: { current: 2, max: 6 },
    latency: 520,
    successRate: 91,
    tasksCompleted: 156,
  },
];
