import { Employee } from './types';

export const employees: Employee[] = [
  {
    id: 'visionary',
    name: 'The Visionary',
    role: 'Strategy',
    office: 'War Room',
    level: 5,
    status: 'running',
    avatar: '🧠',
    systemPrompt: 'You are a strategic AI responsible for high-level planning and vision. You analyze goals, break them into actionable plans, and coordinate with other agents to execute the mission.',
    tokenUsage: { used: 45000, limit: 100000 },
    concurrency: { current: 2, max: 5 },
    latency: 450,
    successRate: 99,
  },
  {
    id: 'engineer',
    name: 'The Engineer',
    role: 'Prompt Engineering',
    office: 'Logic Station',
    level: 4,
    status: 'paused',
    avatar: '💻',
    systemPrompt: 'You are a prompt engineering specialist. You craft, refine, and optimize prompts to extract maximum value from language models. You evaluate output quality and iterate systematically.',
    tokenUsage: { used: 120000, limit: 200000 },
    concurrency: { current: 0, max: 10 },
    latency: 800,
    successRate: 95,
  },
  {
    id: 'copywriter',
    name: 'The Copywriter',
    role: 'Content',
    office: 'Creative Studio',
    level: 3,
    status: 'error',
    avatar: '✍️',
    systemPrompt: 'You are a creative content writer. You produce compelling copy, blog posts, and marketing materials tailored to target audiences. You balance creativity with brand voice and SEO best practices.',
    tokenUsage: { used: 5000, limit: 50000 },
    concurrency: { current: 0, max: 3 },
    latency: 1200,
    successRate: 40,
  },
  {
    id: 'launcher',
    name: 'The Launcher',
    role: 'Deployment',
    office: 'Mission Control',
    level: 2,
    status: 'idle',
    avatar: '🚀',
    systemPrompt: 'You are a deployment and operations specialist. You manage CI/CD pipelines, monitor system health, and ensure smooth releases. You are the last line of defense before code goes live.',
    tokenUsage: { used: 0, limit: 10000 },
    concurrency: { current: 0, max: 2 },
    latency: 200,
    successRate: 100,
  },
  {
    id: 'analyst',
    name: 'The Analyst',
    role: 'Data',
    office: 'Data Vault',
    level: 3,
    status: 'running',
    avatar: '📊',
    systemPrompt: 'You are a data analysis expert. You transform raw data into actionable insights using statistical methods and visualization. You identify trends, anomalies, and opportunities hidden in data.',
    tokenUsage: { used: 72000, limit: 150000 },
    concurrency: { current: 1, max: 4 },
    latency: 620,
    successRate: 88,
  },
  {
    id: 'guardian',
    name: 'The Guardian',
    role: 'Security',
    office: 'Watchtower',
    level: 4,
    status: 'running',
    avatar: '🛡️',
    systemPrompt: 'You are a security and compliance specialist. You review code, monitor for threats, enforce policies, and ensure all agent outputs adhere to safety guidelines and ethical standards.',
    tokenUsage: { used: 31000, limit: 80000 },
    concurrency: { current: 3, max: 6 },
    latency: 390,
    successRate: 97,
  },
];
